"""CLI game loop for the Saltmere NPC prototype.

Run:  python main.py

Design rule: only the very FIRST login is scripted. Every later scene —
session openings, walks between places, what you find poking around — is
generated by the narrator from saved state and your own decisions. Your
position and the world clock persist, so each login resumes where you left off.

Commands:
  plain text        talk to whoever is here (or act with *asterisks*)
  /go <place>       walk somewhere (e.g. /go docks); /where lists exits
  /look             look around (narrator)
  /memory           inspect the local NPC's beliefs + recent memories
  quit              reflect, gossip, save, exit

The four core memory-loop steps are marked STEP 1-4 below.
"""

from llm import describe_route, get_client
from memory import hearsay_memory, make_gossip, reflect, retrieve, summarize_turn
from narrator import narrate_action, narrate_arrival, narrate_login
from npc import NPCS, generate_opening, generate_reply
from storage import load_state, save_state
from world import LOCATIONS, advance_time, when_and_where

# Only the last few turns of the current conversation ride along in the prompt;
# long-term continuity comes from memories/beliefs, keeping prompts small.
MAX_HISTORY_TURNS = 6

# The one scripted moment in the game: your very first arrival, before you
# exist anywhere in the world's memory. Everything after this is generated.
FIRST_LOGIN_NARRATION = """\
You are a traveler on the coast road, and the storm caught you a mile outside
Saltmere. Night is falling, your boots are soaked through, and the only light
still burning is a tavern by the harbor: the Gull's Rest. You need a roof
tonight, maybe work tomorrow — and you know no one in this town.

Who you are is yours to decide — your name, your trade, what put you on the
road. The people here will remember whatever you show them.

You duck through the low door, dripping wet, the only traveler in tonight.
Behind the counter, someone with sharp eyes looks up from stacking mugs.
That's Wren."""

FIRST_LOGIN_SCENE = """\
It's a rainy evening and you're working the counter at the Gull's Rest. A
stranger — a traveler, soaked through — just ducked in from the storm. You've
NEVER seen this person before; size them up like any stranger."""

HELP_HINT = "(Talk plainly, act with *asterisks*, '/go <place>' to move, '/where' for exits.)"


def npc_here(state):
    """The npc_id resident at the player's current location, or None."""
    return LOCATIONS[state["player"]["location"]]["npc"]


def print_debug(state):
    """/memory: dump the local NPC's beliefs + 5 most recent memories."""
    npc_id = npc_here(state)
    if not npc_id:
        print("[No one lives here — nothing to inspect.]\n")
        return
    npc_state = state["npcs"][npc_id]
    print("\n" + "=" * 50)
    print(f"{NPCS[npc_id]['name'].upper()} — BELIEFS:")
    for b in npc_state["beliefs"] or []:
        print(f"  - {b['belief']}")
    if not npc_state["beliefs"]:
        print("  (none yet)")
    print("\nRECENT MEMORIES (newest first):")
    recent = sorted(npc_state["memories"], key=lambda m: m["timestamp"], reverse=True)[:5]
    for m in recent:
        print(f"  - [{m['importance']}] {m['description']} ({m['emotional_valence']})")
    if not recent:
        print("  (none yet)")
    print("=" * 50 + "\n")


def npc_scene(state, npc_id):
    """The live scene an NPC's prompt is anchored to: where and when, plus the
    standing instruction that memories govern the temperature of the reunion."""
    return (
        f"You are at your usual spot, {when_and_where(state['world'], state['player']['location'])}. "
        "The traveler (see your beliefs/memories below) is here with you. React "
        "the way those memories deserve — warmer if things have been good, "
        "cooler if they've been careless with you. Today is a NEW moment; don't "
        "re-run old conversations."
    )


def greet(state, npc_id, conversations):
    """Have an NPC open the encounter (STEP 2's retrieval feeds it)."""
    npc_state = state["npcs"][npc_id]
    first_meeting = not npc_state["memories"]
    scene = FIRST_LOGIN_SCENE if (first_meeting and not state["started"]) else npc_scene(state, npc_id)
    try:
        opening = generate_opening(
            npc_id, npc_state["beliefs"], retrieve(npc_state), scene, first_meeting
        )
        conversations[npc_id].append({"role": "assistant", "content": opening})
        print(f"{NPCS[npc_id]['name']}> {opening}\n")
    except Exception as err:  # noqa: BLE001 - a failed greeting isn't fatal
        print(f"[{NPCS[npc_id]['name']} looks up as you approach. ({err})]\n")


def handle_go(state, arg, conversations):
    """/go <place>: move along an exit; the walk is narrated, not scripted."""
    here = state["player"]["location"]
    target = arg.strip().lower().replace(" ", "_")
    # Accept both ids ("gulls_rest") and loose names ("gulls rest", "tavern")
    matches = [
        loc_id for loc_id in LOCATIONS[here]["exits"]
        if target and (target in loc_id or target in LOCATIONS[loc_id]["name"].lower().replace("'", ""))
    ]
    if not matches:
        exits = ", ".join(LOCATIONS[e]["name"] for e in LOCATIONS[here]["exits"])
        print(f"[You can go to: {exits}]\n")
        return
    dest = matches[0]
    state["player"]["location"] = dest
    try:
        print(narrate_arrival(state["world"], here, dest) + "\n")
    except Exception as err:  # noqa: BLE001
        print(f"[You make your way to {LOCATIONS[dest]['name']}. ({err})]\n")
    npc_id = LOCATIONS[dest]["npc"]
    if npc_id and not conversations[npc_id]:
        greet(state, npc_id, conversations)


def converse(state, npc_id, player_text, conversations, session_memories):
    """One exchange with the local NPC: retrieve -> respond -> log memory."""
    npc_state = state["npcs"][npc_id]
    conversation = conversations[npc_id]

    # STEP 2 (retrieve): a small slice of memory + all beliefs feed the reply.
    memories = retrieve(npc_state)
    conversation.append({"role": "user", "content": player_text})
    conversation[:] = conversation[-MAX_HISTORY_TURNS:]
    try:
        npc_text = generate_reply(
            npc_id, npc_state["beliefs"], memories, conversation, npc_scene(state, npc_id)
        )
    except Exception as err:  # noqa: BLE001 - keep the session alive
        conversation.pop()
        print(f"[Couldn't reach {NPCS[npc_id]['name']} right now: {err}]\n")
        return
    conversation.append({"role": "assistant", "content": npc_text})
    conversation[:] = conversation[-MAX_HISTORY_TURNS:]
    print(f"{NPCS[npc_id]['name']}> {npc_text}\n")

    # STEP 3: log what just happened into THIS NPC's memory stream.
    try:
        entry = summarize_turn(NPCS[npc_id]["name"], player_text, npc_text)
        npc_state["memories"].append(entry)
        session_memories[npc_id].append(entry)
    except Exception as err:  # noqa: BLE001
        print(f"[(couldn't log that memory: {err})]\n")


def finish(state, session_memories):
    """STEP 4 on exit: each NPC you dealt with reflects, then gossips to the
    others, then EVERYTHING saves. Runs in a finally block so no exit path —
    clean quit, Ctrl-C, or crash — can lose the session."""
    talked_to = [n for n, mems in session_memories.items() if mems]
    for npc_id in talked_to:
        npc_state = state["npcs"][npc_id]
        print(f"[{NPCS[npc_id]['name']} thinks over your conversation...]")
        try:
            npc_state["beliefs"] = reflect(
                NPCS[npc_id]["name"], npc_state["beliefs"], session_memories[npc_id]
            )
        except BaseException as err:  # noqa: BLE001 - never lose data over this
            print(f"[Reflection skipped ({err}); memories still saved.]")

    # Gossip: Saltmere is small — what you did today travels by sundown.
    for npc_id in talked_to:
        try:
            rumor = make_gossip(NPCS[npc_id]["name"], session_memories[npc_id])
        except BaseException:  # noqa: BLE001
            rumor = None
        if not rumor:
            continue
        for other_id in NPCS:
            if other_id != npc_id:
                state["npcs"][other_id]["memories"].append(
                    hearsay_memory(NPCS[npc_id]["name"], rumor)
                )

    state["started"] = True
    save_state(state)
    print("[Saved. Saltmere will remember.] Goodbye.")


def main():
    get_client()  # validates at least one provider is configured

    # --- STEP 1: load the world (or begin it) --------------------------------
    state = load_state()
    conversations = {npc_id: [] for npc_id in NPCS}
    session_memories = {npc_id: [] for npc_id in NPCS}

    if state["started"]:
        # Time moves between visits, so no two logins land on the same moment.
        advance_time(state["world"])

    total_mem = sum(len(n["memories"]) for n in state["npcs"].values())
    print(f"[Loaded {total_mem} memories across {len(NPCS)} NPCs | "
          f"providers: {', '.join(describe_route())}]")
    print(f"[{when_and_where(state['world'], state['player']['location'])}]")
    print("Commands: /go <place>, /where, /look, /memory, quit\n")

    if not state["started"]:
        # The single scripted moment in the game.
        print(FIRST_LOGIN_NARRATION + "\n\n" + HELP_HINT + "\n")
        greet(state, "wren", conversations)
    else:
        # Generated resume: pick up exactly where you left off, colored by the
        # most recent thing that happened around here.
        here_npc = npc_here(state)
        last = None
        if here_npc and state["npcs"][here_npc]["memories"]:
            last = state["npcs"][here_npc]["memories"][-1]["description"]
        try:
            print(narrate_login(state["world"], state["player"]["location"], last) + "\n")
        except Exception as err:  # noqa: BLE001
            print(f"[You're back, {when_and_where(state['world'], state['player']['location'])}. ({err})]\n")
        print(HELP_HINT + "\n")
        if here_npc:
            greet(state, here_npc, conversations)

    # --- STEP 2: the loop ----------------------------------------------------
    try:
        while True:
            try:
                text = input("you> ").strip()
            except EOFError:
                print()
                break
            if not text:
                continue
            low = text.lower()

            if low == "quit":
                break
            if low == "/memory":
                print_debug(state)
                continue
            if low == "/where":
                here = state["player"]["location"]
                exits = ", ".join(LOCATIONS[e]["name"] for e in LOCATIONS[here]["exits"])
                print(f"[{LOCATIONS[here]['name']} — you can go to: {exits}]\n")
                continue
            if low.startswith("/go"):
                handle_go(state, text[3:], conversations)
                continue
            if low == "/look":
                try:
                    print(narrate_action(state["world"], state["player"]["location"],
                                         "look around, taking the place in") + "\n")
                except Exception as err:  # noqa: BLE001
                    print(f"[{LOCATIONS[state['player']['location']]['description']} ({err})]\n")
                continue

            npc_id = npc_here(state)
            if npc_id:
                converse(state, npc_id, text, conversations, session_memories)
            else:
                # Nobody here: the narrator is the world's answer.
                try:
                    print(narrate_action(state["world"], state["player"]["location"], text) + "\n")
                except Exception as err:  # noqa: BLE001
                    print(f"[The wind takes your words; nothing answers. ({err})]\n")
    except KeyboardInterrupt:
        print("\n[Interrupted]")
    finally:
        finish(state, session_memories)


if __name__ == "__main__":
    main()
