"""The world of Saltmere: locations, exits, the clock, and world state.

This is the only hand-authored world data. Everything the player *experiences*
of it (scene descriptions, arrivals, what happens when they poke around) is
generated by the narrator (see narrator.py) from this skeleton + saved state —
per the design rule: only the very first login is scripted, everything after is
AI-driven from the player's actual decisions.
"""

SETTING_NAME = "Saltmere"

WORLD_LORE = """\
The world is a low-fantasy realm of kingdoms, guilds, and wandering adventurers
— sails and lanterns and a little old magic, no modern technology (no cars,
phones, or coffee shops). Saltmere is a weathered harbor town on the western
edge of the kingdom of Aldermoor. Travelers pass through chasing work, rumors,
or passage by sea."""

# What the player character actually IS. The referee resolves every *action*
# against these rules, so outcomes are canonical world physics instead of
# whichever NPC happens to be watching. Grant abilities here (and only here)
# if the game ever gives the player powers.
PLAYER_RULES = """\
The traveler is an ordinary human. They have NO magic, NO supernatural
abilities, and ordinary strength — saying words of power does nothing, and
claiming an ability doesn't create it. Wounds, weather, fatigue, and other
people's reactions are all real. They can do anything an ordinary determined
person could physically attempt; attempts can succeed, partly succeed, or
fail, but never break these rules."""

# The map: a handful of places, each with exits and at most one resident NPC.
LOCATIONS = {
    "gulls_rest": {
        "name": "The Gull's Rest",
        "description": "A low-beamed harbor tavern: hearth, scarred tables, "
                       "the smell of woodsmoke and salt.",
        "exits": ["docks", "market"],
        "npc": "wren",
    },
    "docks": {
        "name": "The Docks",
        "description": "Crowded fishing docks — nets, crates, gulls screaming "
                       "over the tide, boats knocking against their moorings.",
        "exits": ["gulls_rest", "market", "coast_road"],
        "npc": "brann",
    },
    "market": {
        "name": "The Market",
        "description": "A handful of stalls in a cobbled square: fish, rope, "
                       "bread, and whatever the last ship brought in.",
        "exits": ["gulls_rest", "docks"],
        "npc": "sera",
    },
    "coast_road": {
        "name": "The Coast Road",
        "description": "The wind-beaten road out of town, running along the "
                       "cliffs toward the capital. Gorse, spray, and distance.",
        "exits": ["docks", "lighthouse"],
        "npc": None,
    },
    "lighthouse": {
        "name": "The Old Lighthouse",
        "description": "A salt-streaked lighthouse above the cliffs, still "
                       "burning at night. Wren grew up here.",
        "exits": ["coast_road"],
        "npc": None,
    },
}

TIMES_OF_DAY = ["morning", "midday", "afternoon", "evening", "night"]


def advance_time(world):
    """Move the world clock one step; each login ticks it so no two visits
    land on the same moment. Rolls over into a new day."""
    world["time_index"] = (world["time_index"] + 1) % len(TIMES_OF_DAY)
    if world["time_index"] == 0:
        world["day"] += 1


def time_of_day(world):
    return TIMES_OF_DAY[world["time_index"]]


def when_and_where(world, location_id):
    """Compact 'day 3, evening, at the Docks' string for prompts and the UI."""
    loc = LOCATIONS[location_id]
    return f"day {world['day']}, {time_of_day(world)}, at {loc['name']}"
