"""The world of Saltmere: locations, exits, the clock, and world state.

This is the only hand-authored world data. Everything the player *experiences*
of it (scene descriptions, arrivals, what happens when they poke around) is
generated by the narrator (see narrator.py) from this skeleton + saved state —
per the design rule: only the very first login is scripted, everything after is
AI-driven from the player's actual decisions.
"""

SETTING_NAME = "Saltmere"

WORLD_LORE = """\
Three generations ago, mana returned to the world. Shimmering rifts called
GATES tear open without warning and spill monsters until someone closes them;
ordinary people sometimes AWAKEN with a mana core and take an adventurer's
license from the Guild, ranked E (fresh) up to S (legendary). Healers are rare
and watched closely — mending flesh borders on the forbidden arts — and rumor
says a hidden order moves in the shadows behind every kingdom. For all that,
daily life stays sails, lanterns, and salted fish: no modern technology.

Saltmere is a weathered harbor town on the western edge of the kingdom of
Aldermoor. An unstable Gate glimmers offshore beyond the old lighthouse — too
small to panic over, too strange to ignore — and it has begun drawing
adventurers, Guild bounties, and trouble to a town that used to see none."""

# Starting abilities for a fresh character: low-rank versions of the classic
# fantasies (a bolt, a heal, a shadow-step). The referee treats this list —
# and only this list — as what the player can genuinely do.
STARTING_ABILITIES = [
    "Spark — hurl a small crackling bolt of mana (stings, scorches; can't demolish)",
    "Mend — slow minor healing by touch (cuts and bruises, not lost limbs)",
    "Shade-step — melt into shadow for a few silent steps (moments, not minutes)",
]


def build_player_rules(player):
    """What the player character actually IS. The referee resolves every
    *action* against these rules, so outcomes are canonical world physics
    instead of whichever NPC happens to be watching. Abilities grow here (and
    only here) as the game grants them."""
    abilities = "\n".join(f"- {a}" for a in player.get("abilities", []))
    return f"""\
{player['name']} is a newly Awakened adventurer — Guild rank E, level
{player.get('level', 1)}, {player.get('gender', 'unspecified')}. They carry a
fresh Guild license and a weak but real mana core.

Abilities they can GENUINELY use, at modest low-rank strength:
{abilities}

Anything beyond that list — grand spells, mind control, erasing memories,
flight, raising the dead, mass destruction — visibly fizzles: their core is
far too weak, and overreach leaves them drained and dizzy. Claiming a power
doesn't create it. Wounds, fatigue, and other people's reactions are real, and
the death of any person is permanent. Words alone never change reality."""

# The map: a handful of places, each with exits and at most one resident NPC.
LOCATIONS = {
    "gulls_rest": {
        "name": "The Gull's Rest",
        "description": "A low-beamed harbor tavern: hearth, scarred tables, "
                       "the smell of woodsmoke and salt.",
        "exits": ["docks", "market"],
        "npc": "wren",
    },
    "docks": {
        "name": "The Docks",
        "description": "Crowded fishing docks — nets, crates, gulls screaming "
                       "over the tide, boats knocking against their moorings.",
        "exits": ["gulls_rest", "market", "coast_road"],
        "npc": "brann",
    },
    "market": {
        "name": "The Market",
        "description": "A handful of stalls in a cobbled square: fish, rope, "
                       "bread, and whatever the last ship brought in.",
        "exits": ["gulls_rest", "docks"],
        "npc": "sera",
    },
    "coast_road": {
        "name": "The Coast Road",
        "description": "The wind-beaten road out of town, running along the "
                       "cliffs toward the capital. Gorse, spray, and — on clear "
                       "nights — a faint wrong-colored glimmer out at sea.",
        "exits": ["docks", "lighthouse"],
        "npc": None,
    },
    "lighthouse": {
        "name": "The Old Lighthouse",
        "description": "A salt-streaked lighthouse above the cliffs, still "
                       "burning at night. Wren grew up here. From the gallery "
                       "you can see the offshore Gate shimmer on the water.",
        "exits": ["coast_road"],
        "npc": None,
    },
}

TIMES_OF_DAY = ["morning", "midday", "afternoon", "evening", "night"]


def advance_time(world):
    """Move the world clock one step; each login ticks it so no two visits
    land on the same moment. Rolls over into a new day."""
    world["time_index"] = (world["time_index"] + 1) % len(TIMES_OF_DAY)
    if world["time_index"] == 0:
        world["day"] += 1


def time_of_day(world):
    return TIMES_OF_DAY[world["time_index"]]


def when_and_where(world, location_id):
    """Compact 'day 3, evening, at the Docks' string for prompts and the UI."""
    loc = LOCATIONS[location_id]
    return f"day {world['day']}, {time_of_day(world)}, at {loc['name']}"
